name: My .NET Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: iisreset /stop
      run: iisreset /stop
    - name: Publish Release
      run: dotnet publish  --configuration Release -o C:\cqrsproj
    - name: Start iis
      run: iisreset /start
      
      
